BotToken:	"telegram token"
ChatId:		chat id(int64)
UrlLogin:	"http://your server/forum/ucp.php?mode=login"
UrlFindNew:	"http://your server/forum/search.php?search_id=unreadposts"
UrlMarkRead:	"http://your server/forum/index.php?mark=forums"
UserName:	"username"
Password:	"password"
